# Generated by Django 5.1.3 on 2024-11-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_bitcoin_purchased_at_alter_silver_purchased_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silver',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
